CHANGE-2583 - adding the schema for the new dates field to the pa-nin…
PressAssociation/schemata pull request #3
Opened 2018-01-31 13:57 UTC by petersow

…js schema

2018-01-31 19:07 UTC, ph0bos requested changes

2018-01-31 19:07 UTC, ph0bos commented on content/ninjs/pa-ninjs-schema_1.0.json
> +          "description": "The period the event will last.",
Maybe add some "duration" example/references here?

2018-02-01 09:58 UTC, gphaydon approved these changes

2018-02-01 10:24 UTC, ph0bos approved these changes

2018-02-01 10:24 UTC, merged